### ISSUE TITLE
Timeseries are removed when associated pod is deleted

### ISSUE THREAD

**Issue by objectiser** [objectiser/opentracing-prometheus-example#40]
Noticed that when pods are scaled down, or the application is removed, it causes the timeseries associated with those pods to be removed from prometheus - i.e. a query of the `span_count` metric no longer returns any data.

In a volatile environment, where pods may be short lived, we need to ensure that any scraped metrics are still retained for further analysis/aggregation.

**Comment by objectiser** [comment]
@krasi-georgiev Any thoughts on this? If you get a chance can you try the instructions for deploying the example to minikube (don't worry about istio), generate some traffic and then query prometheus - and then scale down some of the service instances and see whether you get the same outcome (i.e. some data is removed)?

**Comment by krasi-georgiev** [comment]
this is more on the tsdb side , but will try to replicate and find the culprit.

@simonpasquier  do you know  if this is by design?

**Comment by simonpasquier** [comment]
I have deployed the example (went smoothly, good work on the instructions!). I've scaled down the deployments from 3 replicas to 2 but I don't see anything wrong.

Initially, `sum(span_count) by (job,instance)` returns 6 time-series (one for every pod):
![image](https://user-images.githubusercontent.com/2587585/35619345-076061c8-067e-11e8-9620-31d828fbf595.png)

After scaling down, the same query returns 4 time series:
![image](https://user-images.githubusercontent.com/2587585/35619366-1ab05008-067e-11e8-83ba-814e4da0840f.png)

Doing a range query, I see the series associated to the deleted pods disappearing but that is expected:
![image](https://user-images.githubusercontent.com/2587585/35619396-2f64cfd8-067e-11e8-9d0a-a99b7f6458d0.png)

Am I missing something?

**Comment by objectiser** [comment]
@simonpasquier My mistake, I was only looking at the console view so thought it was strange the timeseries were disappearing, but that was just showing the available timeseries at that point in time I guess - whereas the graph shows the time range and the deleted pod timeseries are still avaliable from a historic view.

Thanks!
